### ISSUE TITLE
Comma triggers autocomplete

### ISSUE THREAD

**Issue by philcruz** [zoo1/autocomplete-cfml#2]
If I type a comma at the end of line it triggers the autocomplete

http://www.screencast.com/t/ozcFsArKNXO

**Comment by zoo1** [comment]
@philcruz thanks for opening an issue! There are actually two things wrong here:
1: tag autocomplete shouldn't occur in the cfscript scope
2: a comma shouldn't trigger autocomplete

**Comment by zoo1** [comment]
@philcruz the fixes for this have been published in the 0.2.3 release
