### ISSUE TITLE
Ending an opening tag shows attribute suggestion list

### ISSUE THREAD

**Issue by jcush** [zoo1/autocomplete-cfml#3]
When typing an opening CF tag, ending with a &gt; causes the code completion list of attributes to appear again, like so:

![image](https://cloud.githubusercontent.com/assets/10184859/20623466/a1cbdb30-b2ff-11e6-8413-af46baec1769.png)

Snipping tool hasn't picked up that my cursor is after the &gt; at this point, but this issue means if I'm typing quickly (and I'm always typing quickly :grin:) then I'll hit enter after the &gt;, which causes the first attribute in the suggestion list to be added, like so:

![image](https://cloud.githubusercontent.com/assets/10184859/20623626/5a355458-b300-11e6-9fe2-25ed93ab9e80.png)

Suggestion: on receiving a &gt; character, the suggestion list should be suppressed where it would normally be shown.

**Comment by jcush** [comment]
Not sure if this would come under the same checks for showing the suggestion list, but also I'm hitting the problem in some odd cases like specifying an alias in a query:

![image](https://cloud.githubusercontent.com/assets/10184859/20623835/75f1430e-b301-11e6-9859-ffd1cb5ab62b.png)

If this needs a new issue opening, however, let me know.

**Comment by zoo1** [comment]
@jcush first of all thanks for opening an issue! If you could split these bugs into two different issues that would be greatly appreciated.😁

**Comment by zoo1** [comment]
@jcush this has been fixed in v0.2.4

**Comment by jcush** [comment]
Tested this out and all seems to be working - thanks for the swift fix! Will open the other issue by the end of the week

**Comment by jcush** [comment]
Opened #4 for the second bug
